# ---------------------------------------------------------------------------
# _gen_css.ps1 — emit the .fhp-* layer for every token left after conversion.
#   reads  : _residual.txt  (produced by _convert.ps1)
#   writes : wwwroot/css/fhp-utilities.css
# Bootstrap owns the utility vocabulary; this file only carries what Bootstrap
# genuinely has no 1:1 class for (exact px values, alpha colours, gradients,
# breakpoint variants of those, hover states, keyframes).
# ---------------------------------------------------------------------------
param([string]$Out = 'f:\.net\FanHubPlus\wwwroot\css\fhp-utilities.css')
$ErrorActionPreference = 'Stop'
. 'f:\.net\FanHubPlus\_convlib.ps1'

$resText = [System.IO.File]::ReadAllText('f:\.net\FanHubPlus\_residual.txt')
$tokens = [System.Collections.Generic.SortedSet[string]]::new()
foreach ($line in ($resText -split "`n")) {
    $t = $line.Trim()
    if (-not $t) { continue }
    $i = $t.IndexOf("`t")
    if ($i -lt 1) { continue }
    $tok = $t.Substring($i + 1).Trim()
    if ($tok -match '^fhp-') { [void]$tokens.Add($tok) }
}
"tokens to emit : " + $tokens.Count

# ---- colour vocabulary (matches the existing site.css palette) ----
$Color = @{
    'white' = '#ffffff'; 'black' = '#000000'
    'body'  = 'var(--fhp-body, #1d2433)'; 'muted' = 'var(--fhp-muted, #6b7280)'
    'primary' = 'var(--bs-primary, #f41b3b)'; 'secondary' = 'var(--bs-secondary, #ffea00)'
    'success' = 'var(--bs-success, #198754)'; 'warning' = 'var(--bs-warning, #ffc107)'
    'danger'  = 'var(--bs-danger, #dc3545)';  'info'    = 'var(--bs-info, #0dcaf0)'
    'navy'    = '#111a2e'; 'cream' = '#f7f3ec'
}

$outSb = New-Object System.Text.StringBuilder
[void]$outSb.AppendLine('/* -------------------------------------------------------------------------')
[void]$outSb.AppendLine('   fhp-utilities.css — generated by _gen_css.ps1. Do not edit by hand.')
[void]$outSb.AppendLine('   Bootstrap 5.3 covers the layout/utility vocabulary; this file carries')
[void]$outSb.AppendLine('   only the exact values, alpha colours, gradients and breakpoint')
[void]$outSb.AppendLine('   variants that have no native Bootstrap class.')
[void]$outSb.AppendLine('   ------------------------------------------------------------------------- */')
[void]$outSb.AppendLine('')
[void]$outSb.AppendLine(':root {')
foreach ($k in ($Color.Keys | Sort-Object)) {
    if ($k -in @('white', 'black')) { continue }
    [void]$outSb.AppendLine("  --fhp-$k : $($Color[$k]);")
}
[void]$outSb.AppendLine('}')
[void]$outSb.AppendLine('')

$PropMap = [ordered]@{
    'm'  = 'margin';       'mx' = 'margin-inline'; 'my' = 'margin-block'
    'mt' = 'margin-top';   'mb' = 'margin-bottom'
    'ml' = 'margin-left';  'mr' = 'margin-right'
    'p'  = 'padding';      'px' = 'padding-inline'; 'py' = 'padding-block'
    'pt' = 'padding-top';  'pb' = 'padding-bottom'
    'pl' = 'padding-left'; 'pr' = 'padding-right'
    'w'  = 'width';        'h'  = 'height'
    'minw' = 'min-width';  'maxw' = 'max-width'
    'minh' = 'min-height'; 'maxh' = 'max-height'
    'top' = 'top';         'bottom' = 'bottom'
    'left' = 'left';       'right' = 'right'
    'inset' = 'inset';     'z' = 'z-index'
}

function Get-SizeVal([string]$v) {
    if ($v -eq 'full') { return '100%' }
    if ($v -eq 'screen') { return '100vh' }
    if ($v -eq 'auto') { return 'auto' }
    if ($v -match '^n(\d+(?:\.\d+)?)$') { return '-' + $Matches[1] + '%' }
    if ($v -match '^(\d+(?:\.\d+)?)$') { return $Matches[1] + 'px' }
    return $null
}
function Get-GColVal([string]$slug) {
    $map = @{
        'repeat-2' = 'repeat(2, minmax(0, 1fr))'
        'repeat-3' = 'repeat(3, minmax(0, 1fr))'
        'repeat-4' = 'repeat(4, minmax(0, 1fr))'
        'repeat-5' = 'repeat(5, minmax(0, 1fr))'
        'repeat-6' = 'repeat(6, minmax(0, 1fr))'
    }
    if ($map.ContainsKey($slug)) { return $map[$slug] }
    return $null
}
function Get-PropVal([string]$prop, [string]$v) {
    if ($v -eq 'full')  { return '100%' }
    if ($v -eq 'screen'){ return '100vh' }
    if ($v -eq 'auto')  { return 'auto' }
    if ($v -eq 'px')    { return '1px' }
    if ($v -eq '0')     { return '0' }
    if ($v -match '^n(\d+(?:\.\d+)?)$') { return '-' + $Matches[1] + 'px' }
    if ($v -match '^(\d+(?:\.\d+)?)pct$') { return $Matches[1] + '%' }
    if ($v -match '^(\d+(?:\.\d+)?)$')  { return $Matches[1] + 'px' }
    return $null
}

$Rules   = New-Object System.Collections.Generic.List[string]
$Queries = @{ sm='576px'; md='768px'; lg='992px'; xl='1200px'; xxl='1400px' }

function Get-Resp([string]$name) {
    if ($name -match '^fhp-(sm|md|lg|xl|xxl)-(.+)$') {
        return @{ Bp = $Matches[1]; Core = 'fhp-' + $Matches[2] }
    }
    return $null
}

$Base = New-Object System.Collections.Generic.List[string]
$Hover = New-Object System.Collections.Generic.List[string]
$GroupHover = New-Object System.Collections.Generic.List[string]
$RESP = New-Object System.Collections.Generic.List[object]
foreach ($name in $tokens) {
    $r = Get-Resp $name
    if ($r) { $RESP.Add([pscustomobject]@{ Cls = $name; Bp = $r.Bp; Core = $r.Core }) }
    elseif ($name -match '^fhp-group-hover-(.+)$') { $GroupHover.Add($name) }
    elseif ($name -match '^fhp-(hover|focus|last|ltr|rtl|first)-(.+)$') { $Hover.Add($name) }
    else    { $Base.Add($name) }
}

$KnownColor = @{
    white='#ffffff'; black='#000000'; transparent='transparent'; current='currentColor'
    navy='#111a2e'; cream='#f7f3ec'
    body='var(--fhp-body, #1d2433)'; muted='var(--fhp-muted, #6b7280)'
    primary='var(--bs-primary)'; secondary='var(--bs-secondary)'; success='var(--bs-success)'
    warning='var(--bs-warning)'; danger='var(--bs-danger)'; info='var(--bs-info)'
    light='var(--bs-light)'; dark='var(--bs-dark)'; gray='var(--bs-gray)'; grey='var(--bs-gray)'
}

# "white-60" -> rgba(255,255,255,.6)   |   "primary-30" -> rgba(var, .3)
function Get-ColorDecl([string]$v, [string]$prop) {
    $alpha = $null
    if ($v -match '^(?<n>.+?)-(?<a>\d+)$' -and $KnownColor.ContainsKey($Matches['n'])) {
        $alpha = [double]$Matches['a']
        $v = $Matches['n']
    }
    if ($KnownColor.ContainsKey($v)) { $hex = $KnownColor[$v] }
    elseif ($v -match '^#([0-9a-fA-F]{3})$')   { $hex = '#' + $Matches[1] }
    elseif ($v -match '^#([0-9a-fA-F]{6})$')   { $hex = '#' + $Matches[1] }
    elseif ($v -match '^[0-9a-fA-F]{3}$')      { $hex = '#' + $v }
    elseif ($v -match '^[0-9a-fA-F]{6}$')      { $hex = '#' + $v }
    else { return $null }
    $final = $hex
    if ($null -ne $alpha) {
        $al = [math]::Round($alpha / 100, 3)
        if ($hex -match '^#([0-9a-fA-F]{6})$') {
            $h = $Matches[1]
            $r2 = [Convert]::ToInt32($h.Substring(0,2),16)
            $g2 = [Convert]::ToInt32($h.Substring(2,2),16)
            $b2 = [Convert]::ToInt32($h.Substring(4,2),16)
            $final = "rgba($r2, $g2, $b2, $al)"
        } else {
            $final = "color-mix(in srgb, $hex $([int]$alpha)%, transparent)"
        }
    }
    if ($prop) { return "$prop`: $final;" }
    return $final
}

$PM = @{
    m='margin'; mt='margin-top'; mb='margin-bottom'; ml='margin-left'; mr='margin-right'
    mx='margin-inline'; my='margin-block'
    p='padding'; pt='padding-top'; pb='padding-bottom'; pl='padding-left'; pr='padding-right'
    px='padding-inline'; py='padding-block'
    w='width'; h='height'; minw='min-width'; maxw='max-width'; minh='min-height'; maxh='max-height'
    top='top'; bottom='bottom'; left='left'; right='right'; inset='inset'
    z='z-index'; gap='gap'; gapx='column-gap'; gapy='row-gap'
}

# token -> CSS declaration.  Returns $null when the token needs a bespoke rule.
function Resolve-Decl([string]$cls) {
    if (-not $cls.StartsWith('fhp-')) { return $null }
    $b = $cls.Substring(4)
    $accent = $false
    if ($b.StartsWith('accent-')) { $accent = $true; $b = $b.Substring(7) }

    # ---------- colours ----------
    if ($b -match '^text-(.+)$')  { $d = Get-ColorDecl $Matches[1] $(if($accent){'accent-color'}else{'color'}); if ($d) { return $d } }
    if ($b -match '^bg-(.+)$')    { $d = Get-ColorDecl $Matches[1] $(if($accent){'accent-color'}else{'background-color'}); if ($d) { return $d } }
    if ($b -match '^borderc-(.+)$'){ $d = Get-ColorDecl $Matches[1] 'border-color'; if ($d) { return $d } }
    if ($b -match '^border-(.+)$') { $d = Get-ColorDecl $Matches[1] 'border-color'; if ($d) { return $d } }

    # ---------- font-size / letter-spacing ----------
    if ($b -match '^fs-(\d+(?:\.\d+)?)$')        { return "font-size: $($Matches[1])px;" }
    if ($b -match '^tracking-(\d+)-(\d+)em$')    { return "letter-spacing: 0.$($Matches[1])$($Matches[2])em;" }
    if ($b -match '^ls-(\w+)$') {
        $ls = @{ wide='.025em'; wider='.05em'; widest='.1em'; tight='-.025em'; tighter='-.05em'; normal='normal' }
        if ($ls.ContainsKey($Matches[1])) { return "letter-spacing: $($ls[$Matches[1]]);" }
    }

    # ---------- radius / border width ----------
    if ($b -match '^r([a-z]{1,2})-(\d+(?:\.\d+)?)$') {
        $mm = @{
            t='top'; b='bottom'; l='left'; r='right'
            tb='top bottom'; lr='left right'; tl='top left'; tr='top right'
            bl='bottom left'; br='bottom right'; ss='top left'; ee='bottom right'
        }
        $k = $Matches[1]
        if ($mm.ContainsKey($k)) { return "border-$($mm[$k])-radius: $($Matches[2])px;" }
    }
    if ($b -match '^r-(\d+(?:\.\d+)?)$') { return "border-radius: $($Matches[1])px;" }
    if ($b -match '^bw-(\d+(?:\.\d+)?)$')  { return "border-width: $($Matches[1])px;" }
    if ($b -eq 'border-dashed') { return 'border-style: dashed;' }
    if ($b -eq 'border-dotted') { return 'border-style: dotted;' }
    if ($b -eq 'border-solid')  { return 'border-style: solid;' }
    if ($b -eq 'border-none')   { return 'border-style: none;' }

    # ---------- spacing & sizing ----------
    if ($b -match '^(m|mt|mb|ml|mr|mx|my|p|pt|pb|pl|pr|px|py|w|h|minw|maxw|minh|maxh|top|bottom|left|right|inset|z|gap|gapx|gapy)-(.+)$') {
        $k = $Matches[1]; $v = $Matches[2]
        $val = Get-PropVal $k $v
        if ($null -ne $val -and $PM.ContainsKey($k)) {
            if ($k -eq 'z') { return "z-index: $val;" }
            return "$($PM[$k]): $val;"
        }
    }

    # ---------- aspect ratio / grid ----------
    if ($b -match '^aspect-(\d+)-(\d+)$') { return "aspect-ratio: $($Matches[1]) / $($Matches[2]);" }
    if ($b -eq 'aspect-square') { return 'aspect-ratio: 1 / 1;' }
    if ($b -eq 'aspect-wide')   { return 'aspect-ratio: 16 / 9;' }
    if ($b -eq 'aspect-tall')   { return 'aspect-ratio: 4 / 5;' }
    if ($b -match '^gcol-(.+)$') { $g = Get-GColVal $Matches[1]; if ($g) { return "grid-template-columns: $g;" } }
    if ($b -match '^gspan-(\d+)$') { return "grid-column: span $($Matches[1]) / span $($Matches[1]);" }
    if ($b -eq 'gspan-full') { return 'grid-column: 1 / -1;' }
    if ($b -match '^gcol-(\d+)$')  { return "grid-template-columns: repeat($($Matches[1]), minmax(0, 1fr));" }

    # ---------- translate ----------
    if ($b -match '^t([xy])-(n?)(\d+(?:\.\d+)?)$') {
        $ax = $Matches[1]; $sg = if ($Matches[2]) { '-' } else { '' }; $n = $Matches[3]
        return "--fhp-t$ax`: $sg$n%;`ntransform: translate(var(--fhp-tx, 0), var(--fhp-ty, 0));"
    }
    # ---------- transform family ----------
    if ($b -eq 'transform')      { return 'transform: translate(var(--fhp-tx, 0), var(--fhp-ty, 0));' }
    if ($b -eq 'transform-none') { return 'transform: none;' }
    if ($b -eq 'transform-gpu')  { return 'transform: translateZ(0);' }
    if ($b -eq 'transform-cpu')  { return 'transform: translateZ(0);' }
    if ($b -match '^origin-(\w+)$')   { return "transform-origin: $($Matches[1]);" }
    if ($b -match '^rotate-(\d+)$')    { return "transform: translate(var(--fhp-tx,0),var(--fhp-ty,0)) rotate($($Matches[1])deg);" }
    if ($b -match '^nrotate-(\d+)$')   { return "transform: translate(var(--fhp-tx,0),var(--fhp-ty,0)) rotate(-$($Matches[1])deg);" }
    if ($b -match '^scale-(\d+(?:\.\d+)?)$') { return "transform: translate(var(--fhp-tx,0),var(--fhp-ty,0)) scale($($Matches[1]));" }
    # ---------- transition ----------
    $TP = 'transition-property: all; transition-timing-function: cubic-bezier(.4,0,.2,1); transition-duration: 300ms;'
    if ($b -eq 'transition') { return $TP }
    if ($b -match '^transition-(all|colors|opacity|transform|shadow|none|filter)$') { return "transition-property: $($Matches[1]); transition-timing-function: cubic-bezier(.4,0,.2,1); transition-duration: 300ms;" }
    if ($b -match '^dur(\d+)$') { return "transition-duration: $($Matches[1])ms;" }
    if ($b -eq 'delay-0')       { return 'transition-delay: 0ms;' }
    if ($b -match '^delay-(\d+)$'){ return "transition-delay: $($Matches[1])ms;" }
    if ($b -match '^ease-(in|out|inout|linear|initial)$') { return 'transition-timing-function: cubic-bezier(.4,0,.2,1);' }
    if ($b -match '^ease-(in|out|inout)$') { return "transition-timing-function: cubic-bezier(.4,0,.2,1);" }
    # ---------- effects ----------
    if ($b -match '^backdrop-blur(.*)$') { return '-webkit-backdrop-filter: blur(8px); backdrop-filter: blur(8px);' }
    if ($b -match '^shadow-(.+)$') {
        $sh = @{
            'sm'='0 1px 2px rgba(0,0,0,.06)'; 'md'='0 4px 10px rgba(0,0,0,.08)'
            'lg'='0 10px 30px rgba(0,0,0,.12)'; 'xl'='0 20px 50px rgba(0,0,0,.16)'
            '2xl'='0 30px 80px rgba(0,0,0,.20)'; 'inner'='inset 0 2px 4px rgba(0,0,0,.08)'
        }
        if ($sh.ContainsKey($Matches[1])) { return "box-shadow: $($sh[$Matches[1]]);" }
    }
    if ($b -match '^weight-(\d+)$') { return "font-weight: $($Matches[1]);" }
    if ($b -match '^leading-(\d+(?:\.\d+)?)$') { return "line-height: $($Matches[1]);" }
    if ($b -match '^opacity-(\d+(?:\.\d+)?)$') { return "opacity: $($Matches[1]);" }

    # ---------- named singles ----------
    $N = @{
        'cursor-pointer'='cursor: pointer;'; 'cursor-not-allowed'='cursor: not-allowed;'
        'cursor-default'='cursor: default;'; 'cursor-grab'='cursor: grab;'
        'cursor-grabbing'='cursor: grabbing;'; 'cursor-wait'='cursor: wait;'
        'cursor-help'='cursor: help;'; 'cursor-text'='cursor: text;'
        'cursor-move'='cursor: move;'; 'cursor-crosshair'='cursor: crosshair;'
        'cursor-cell'='cursor: cell;'; 'cursor-copy'='cursor: copy;'
        'cursor-alias'='cursor: alias;'; 'cursor-progress'='cursor: progress;'
        'cursor-zoom-in'='cursor: zoom-in;'; 'cursor-zoom-out'='cursor: zoom-out;'
        'select-none'='user-select: none;'; 'select-text'='user-select: text;'
        'select-all'='user-select: all;'; 'select-auto'='user-select: auto;'
        'pointer-events-none'='pointer-events: none;'; 'pointer-events-auto'='pointer-events: auto;'
        'resize-none'='resize: none;'; 'resize-both'='resize: both;'
        'resize'='resize: both;'; 'resize-x'='resize: horizontal;'
        'resize-y'='resize: vertical;'
        'appearance-none'='appearance: none;'; 'list-none'='list-style: none;'
        'list-disc'='list-style-type: disc;'; 'list-decimal'='list-style-type: decimal;'
        'underline'='text-decoration: underline;'; 'overline'='text-decoration: overline;'
        'line-through'='text-decoration: line-through;'; 'no-underline'='text-decoration: none;'
        'uppercase'='text-transform: uppercase;'; 'lowercase'='text-transform: lowercase;'
        'capitalize'='text-transform: capitalize;'; 'normal-case'='text-transform: none;'
        'align-start'='vertical-align: top;'; 'align-end'='vertical-align: bottom;'
        'align-center'='vertical-align: middle;'; 'align-baseline'='vertical-align: baseline;'
        'align-top'='vertical-align: top;'; 'align-bottom'='vertical-align: bottom;'
        'flex-row'='flex-direction: row;'; 'flex-row-reverse'='flex-direction: row-reverse;'
        'flex-col'='flex-direction: column;'; 'flex-col-reverse'='flex-direction: column-reverse;'
        'flex-wrap'='flex-wrap: wrap;'; 'flex-nowrap'='flex-wrap: nowrap;'
        'flex-wrap-reverse'='flex-wrap: wrap-reverse;'
        'grow'='flex-grow: 1;'; 'shrink'='flex-shrink: 1;'
        'grid'='display: grid;'; 'inline-grid'='display: inline-grid;'
        'block'='display: block;'; 'inline-block'='display: inline-block;'
        'inline'='display: inline;'; 'table'='display: table;'
        'table-cell'='display: table-cell;'; 'table-row'='display: table-row;'
        'table-flex'='display: table-flex;'; 'table-auto'='width: auto;'
        'float-left'='float: left;'; 'float-right'='float: right;'
        'float-none'='float: none;'
        'clear-left'='clear: left;'; 'clear-right'='clear: right;'
        'clear-both'='clear: both;'
        'invisible'='visibility: hidden;'; 'visible'='visibility: visible;'
        'collapse'='visibility: collapse;'
        'italic'='font-style: italic;'; 'not-italic'='font-style: normal;'
        'bold'='font-weight: 700;'; 'black'='font-weight: 900;'
        'nowrap'='white-space: nowrap;'; 'wrap'='white-space: normal;'
        'break-words'='overflow-wrap: break-word;'; 'break-all'='word-break: break-all;'
        'break-normal'='overflow-wrap: normal;'
        'antialiased'='-webkit-font-smoothing: antialiased;'
        'subpixel'='-webkit-font-smoothing: subpixel-antialiased;'
        'tabular'='font-variant-numeric: tabular-nums;'; 'nums'='font-variant-numeric: tabular-nums;'
        'outline-none'='outline: 0; box-shadow: none;'
        'object-cover'='object-fit: cover;'; 'object-contain'='object-fit: contain;'
        'object-fill'='object-fit: fill;'; 'object-none'='object-fit: none;'
        'object-center'='object-position: center;'; 'object-scale-down'='object-fit: scale-down;'
        'bg-cover'='background-position: center; background-size: cover;'
        'bg-contain'='background-position: center; background-size: contain;'
        'bg-center'='background-position: center;'; 'bg-top'='background-position: top;'
        'bg-bottom'='background-position: bottom;'; 'bg-left'='background-position: left;'
        'bg-right'='background-position: right;'; 'bg-auto'='background-position: auto;'
        'bg-norepeat'='background-repeat: no-repeat;'; 'bg-repeat'='background-repeat: repeat;'
        'bg-repeat-x'='background-repeat: repeat-x;'; 'bg-repeat-y'='background-repeat: repeat-y;'
        'bg-fixed'='background-attachment: fixed;'; 'bg-local'='background-attachment: local;'
        'bg-scroll'='background-attachment: scroll;'
        'bg-clip-border'='background-clip: border-box;'; 'bg-clip-padding'='background-clip: padding-box;'
        'bg-clip-content'='background-clip: content-box;'; 'bg-none'='background-image: none;'
        'basis-full'='flex-basis: 100%;'; 'basis-auto'='flex-basis: auto;'
        'basis-0'='flex-basis: 0;'
        'shadow-none'='box-shadow: none;'
    }
    if ($N.ContainsKey($b)) { return $N[$b] }

    # ---------- gradients ----------
    $GDir = @{ r='to right'; l='to left'; t='to bottom'; b='to top'; tr='to top right'; tl='to top left';
               br='to bottom right'; bl='to bottom left'; none='none' }
    if ($b -match '^grad-(r|l|t|b|tr|tl|br|bl|none)$') { return "background-image: linear-gradient($($GDir[$Matches[1]]));" }
    if ($b -match '^from-(.+)$') { $d = Get-ColorDecl $Matches[1] $null; if ($d) { return "--fhp-grad-from: $d;" } }
    if ($b -match '^via-(.+)$')  { $d = Get-ColorDecl $Matches[1] $null; if ($d) { return "--fhp-grad-via: $d;" } }
    if ($b -match '^to-(.+)$')   { $d = Get-ColorDecl $Matches[1] $null; if ($d) { return "--fhp-grad-to: $d;" } }

    # ---------- divide / space (needs a wrapper, emitted as <*>-y) ----------
    if ($b -eq 'divide-y') { return 'border-top-width: 1px solid currentColor; border-bottom-width: 0;' }
    if ($b -eq 'divide-x') { return 'border-left-width: 1px solid currentColor; border-right-width: 0;' }
    if ($b -match '^divide-(.+)$') { $d = Get-ColorDecl $Matches[1] $null; if ($d) { return "border-color: $d;" } }
    if ($b -match '^space-y-(\d+(?:\.\d+)?)$') { return "row-gap: $($Matches[1])rem;" }
    if ($b -match '^space-x-(\d+(?:\.\d+)?)$') { return "column-gap: $($Matches[1])rem;" }
    if ($b -match '^me-(\d+(?:\.\d+)?)$') { return "margin-inline-end: $($Matches[1])rem;" }
    if ($b -match '^ms-(\d+(?:\.\d+)?)$') { return "margin-inline-start: $($Matches[1])rem;" }
    if ($b -match '^pe-(\d+(?:\.\d+)?)$') { return "padding-inline-end: $($Matches[1])rem;" }
    if ($b -match '^ps-(\d+(?:\.\d+)?)$') { return "padding-inline-start: $($Matches[1])rem;" }

    # ---------- assorted shapes / misc ----------
    if ($b -match '^[01]?[0-9]?px$') { return "$(if($b -eq '1px'){'1px'}else{'0'});" }
    if ($b -match '^r-(t|b)-(\d+)$') {
        $mm = @{ t='top'; b='bottom' }
        return "border-$($mm[$Matches[1]])-radius: $($Matches[2])px;"
    }
    if ($b -match '^line-clamp-(\d+)$') {
        return "display: -webkit-box; -webkit-line-clamp: $($Matches[1]); -webkit-box-orient: vertical; overflow: hidden;"
    }
    if ($b -match '^leading-(\d+)-(\d+)$') { return "line-height: $([double]$Matches[1] / [double]$Matches[2]);" }
    if ($b -match '^font-(primary|secondary|body|muted|mono)$') {
        $ff = @{
            primary='var(--fhp-font-primary)'; secondary='var(--fhp-font-secondary)'
            body='var(--fhp-body-font)'; muted='var(--fhp-muted-font)'; mono='var(--fhp-font-mono)'
        }
        return "font-family: $($ff[$Matches[1]]);"
    }
    if ($b -eq 'spin')          { return 'animation: fhp-spin 1s linear infinite;' }
    if ($b -eq 'pulse')         { return 'animation: fhp-pulse 2s ease-in-out infinite;' }
    if ($b -eq 'ping')          { return 'animation: fhp-ping 1s cubic-bezier(0,0,.2,1) infinite;' }
    if ($b -eq 'bounce')        { return 'animation: fhp-bounce 1s infinite;' }
    if ($b -eq 'ease')          { return 'transition-timing-function: cubic-bezier(.4,0,.2,1);' }
    if ($b -eq 'rotate-me')     { return 'animation: fhp-rotateme 12s linear infinite;' }
    if ($b -eq 'rotateme')      { return 'animation: fhp-rotateme 12s linear infinite;' }
    if ($b -eq 'text-animation'){ return 'animation: fhp-texteffect 4s ease-in-out infinite;' }
    if ($b -eq 'is-active-cat') { return 'color: var(--bs-primary); font-weight: 700;' }
    if ($b -eq 'is-active-state') { return 'opacity: 1; visibility: visible;' }
    if ($b -eq 'is')            { return $null }     # polymorphic JS hook
    if ($b -eq 'group')         { return $null }     # JS hook: marks the group-hover parent
    if ($b -eq 'admin-nav')     { return $null }     # JS hook toggled by the admin shell
    if ($b -eq 'share')         { return $null }     # JS hook for the share button
    if ($b -eq 'with-border')   { return 'border: 1px solid var(--fhp-body, #1d2433);' }
    if ($b -eq 'backdrop')      { return 'backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px);' }
    if ($b -eq 'scrollbar')     { return 'scrollbar-width: thin; scrollbar-color: var(--fhp-scroll-thumb, #c9cedb) transparent;' }
    if ($b -eq 'd-block')       { return 'display: block;' }
    if ($b -eq 'justify-start') { return 'justify-content: flex-start;' }
    if ($b -eq 'mx-auto')       { return 'margin-inline: auto;' }
    if ($b -eq 'mx-0')          { return 'margin-inline: 0;' }
    if ($b -eq 'mb-0')          { return 'margin-bottom: 0;' }
    if ($b -eq 'mt-0')          { return 'margin-top: 0;' }
    if ($b -eq 'h-100')         { return 'height: 100%;' }

    # ---------- late / direct cases ----------
    if ($accent) { $d = Get-ColorDecl $b $null; if ($d) { return "accent-color: $d;" } }
    if ($b -match '^border-(t|b|s|e|r|l|ss|ee)-(.+)$') {
        $mm = @{ t='top'; b='bottom'; s='left'; e='right'; r='right'; l='left'; ss='left'; ee='right' }
        $d = Get-ColorDecl $Matches[2] $null
        if ($d) { return "border-$($mm[$Matches[1]])-color: $d;" }
    }
    if ($b -match '^[01]px$')            { return "$(if($b -eq '1px'){'1px'}else{'0'});" }
    if ($b -match '^(top|bottom|left|right|inset)-(\d+)(px|rem|em|%)?$') {
        $mm = @{ top='top'; bottom='bottom'; left='left'; right='right'; inset='inset' }
        $u = if ($Matches[3]) { $Matches[3] } else { 'px' }
        return "$($mm[$Matches[1]]): $($Matches[2])$u;"
    }
    if ($b -match '^(h|w|minh|minw|maxh|maxw)-(\d+)(px|rem|%)?$') {
        $mm = @{ h='height'; w='width'; minh='min-height'; minw='min-width'; maxh='max-height'; maxw='max-width' }
        $u = if ($Matches[3]) { $Matches[3] } else { 'px' }
        return "$($mm[$Matches[1]]): $($Matches[2])$u;"
    }
    if ($b -match '^r-(rb|tl|tr|bl|br|lr)-(\d+(?:\.\d+)?)$') {
        $mm = @{ rb='bottom'; tr='top right'; tl='top left'; bl='bottom left'; br='bottom right'; lr='left' }
        return "border-$($mm[$Matches[1]])-radius: $($Matches[2])px;"
    }
    if ($b -match '^r-(rb|tl|tr|bl|br|lr|t|b)-(\d+(?:\.\d+)?)$') {
        $mm = @{ rb='bottom'; tr='top right'; tl='top left'; bl='bottom left'
                 br='bottom right'; lr='left'; t='top'; b='bottom' }
        return "border-$($mm[$Matches[1]])-radius: $($Matches[2])px;"
    }
    if ($b -eq 'translate-y-full') { return 'transform: translateY(100%);' }
    if ($b -eq 'translate-y-0')    { return 'transform: translateY(0);' }
    if ($b -match '^translate-y-(\d+)$') { return "transform: translateY($($Matches[1])px);" }
    if ($b -eq 'translate-x-full') { return 'transform: translateX(100%);' }

    if ($b -eq 'group')     { return $null }     # JS hook only, no styling
    if ($b -match '^(nav|admin-nav|nav__dropdown|nav__searchbox|share|num)$') { return $null }
    if ($b -match '^pill--') { return $null }     # markup artefact
    if ($b -eq 'bg-url')    { return $null }     # url() is inline in the markup
    return $null
}

# ============================ WRITE THE FILE ===============================
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('/* =========================================================================')
[void]$sb.AppendLine('   fhp-utilities.css  —  generated by _gen_css.ps1.  Do not hand-edit.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('   Bootstrap 5.3 provides the layout + utility vocabulary for this site.')
[void]$sb.AppendLine('   This file carries ONLY what Bootstrap has no 1:1 class for:')
[void]$sb.AppendLine('     • exact pixel values   (Bootstrap spacing is a fixed rem scale)')
[void]$sb.AppendLine('     • alpha colours        (text-white/60, bg-primary/20, ...)')
[void]$sb.AppendLine('     • gradients            (from-*, via-*, to-*)')
[void]$sb.AppendLine('     • breakpoint variants of the above (fhp-md-*, fhp-lg-*, ...)')
[void]$sb.AppendLine('   Everything is plain CSS layered on Bootstrap: no build step, no')
[void]$sb.AppendLine('   framework, no Tailwind.  Regenerate with:')
[void]$sb.AppendLine('       powershell -File _convert.ps1 -Apply; powershell -File _gen_css.ps1')
[void]$sb.AppendLine('   ========================================================================= */')
[void]$sb.AppendLine('')
[void]$sb.AppendLine(':root {')
[void]$sb.AppendLine('  --fhp-body-font: var(--bs-body-font-family);')
[void]$sb.AppendLine('  --fhp-muted-font: var(--bs-body-font-family);')
[void]$sb.AppendLine('  --fhp-font-primary: var(--bs-body-font-family);')
[void]$sb.AppendLine('  --fhp-font-secondary: var(--bs-body-font-family);')
[void]$sb.AppendLine('  --fhp-font-mono: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;')
[void]$sb.AppendLine('}')
[void]$sb.AppendLine('')

# ---- keyframes for the animation helpers ----
[void]$sb.AppendLine('@keyframes fhp-spin { to { transform: rotate(360deg); } }')
[void]$sb.AppendLine('@keyframes fhp-pulse { 0%, 100% { opacity: 1; } 50% { opacity: .5; } }')
[void]$sb.AppendLine('@keyframes fhp-ping { 75%, 100% { transform: scale(2); opacity: 0; } }')
[void]$sb.AppendLine('@keyframes fhp-bounce { 0%, 100% { transform: translateY(-25%); } 50% { transform: translateY(0); } }')
[void]$sb.AppendLine('@keyframes fhp-rotateme { to { transform: rotate(360deg); } }')
[void]$sb.AppendLine('@keyframes fhp-texteffect { 0%, 100% { opacity: 1; } 50% { opacity: .35; } }')
[void]$sb.AppendLine('')

# --- markers: JS-only hooks, deliberately unstyled ---
# .fhp-group  parents the .fhp-group-hover-* rules below
# .fhp-share / .fhp-admin-nav / .fhp-is  are toggled by site.js
[void]$sb.AppendLine('/* ---- JS-only hook markers (intentionally no styling) ---- */')
[void]$sb.AppendLine('.fhp-group, .fhp-share, .fhp-admin-nav, .fhp-is {}')
[void]$sb.AppendLine('')

# ---- gradients that combine a direction with from/via/to stops ----
$grads = New-Object System.Collections.Generic.List[string]
foreach ($name in $BASE) {
    if ($name -match '^fhp-grad-') { $grads.Add($name) }
}
if ($grads.Count) {
    [void]$sb.AppendLine('/* ---- gradient directions (paired with fhp-from-*/fhp-to-* stops) ---- */')
    $GDir = @{ r='to right'; l='to left'; t='to bottom'; b='to top'; tr='to top right'; tl='to top left';
               br='to bottom right'; bl='to bottom left'; none='none' }
    foreach ($g in ($grads | Sort-Object)) {
        $dir = $g.Substring(9)
        $d = if ($GDir.ContainsKey($dir)) { $GDir[$dir] } else { 'to right' }
        [void]$sb.AppendLine(".$g {")
        [void]$sb.AppendLine("  background-image: linear-gradient($d, var(--fhp-grad-from, transparent), var(--fhp-grad-via, transparent), var(--fhp-grad-to, transparent));")
        [void]$sb.AppendLine('}')
    }
    [void]$sb.AppendLine('')
}

# logical-property tokens that need the state wrapper rather than a plain rule
function Resolve-Logical([string]$st, [string]$inner) {
    if ($st -eq 'last') {
        if ($inner -eq 'mb-0')  { return 'margin-bottom: 0;' }
        if ($inner -eq 'mt-0')  { return 'margin-top: 0;' }
        if ($inner -match '^mb-(\d+)px$') { return "margin-bottom: $($Matches[1])px;" }
    }
    $lm = @{
        'start-0'      = 'inset-inline-start: 0;'
        'end-0'        = 'inset-inline-end: 0;'
        'text-start'   = 'text-align: start;'
        'text-end'     = 'text-align: end;'
        'border-start' = 'border-inline-start: 1px solid;'
        'border-end'   = 'border-inline-end: 1px solid;'
        'ml-5px'       = 'margin-inline-start: 5px;'
        'mr-5px'       = 'margin-inline-end: 5px;'
        'ms-5px'       = 'margin-inline-start: 5px;'
        'me-5px'       = 'margin-inline-end: 5px;'
    }
    if ($lm.ContainsKey($inner)) { return $lm[$inner] }
    if ($inner -match '^([mp][lrsexy])-(\d+)px$') {
        $mp = @{
            'ml'='margin-inline-start'; 'mr'='margin-inline-end'
            'ms'='margin-inline-start'; 'me'='margin-inline-end'
            'pl'='padding-inline-start'; 'pr'='padding-inline-end'
            'ps'='padding-inline-start'; 'pe'='padding-inline-end'
        }
        return "$($mp[$Matches[1]]): $($Matches[2])px;"
    }
    if ($inner -match '^(left|right)-(\d+)px$') {
        $lp = if ($Matches[1] -eq 'left') { 'inset-inline-start' } else { 'inset-inline-end' }
        return "$lp`: $($Matches[2])px;"
    }
    if ($inner -match '^(left|right)-auto$') {
        $lp = if ($Matches[1] -eq 'left') { 'inset-inline-start' } else { 'inset-inline-end' }
        return "$lp`: auto;"
    }
    if ($inner -eq 'text-decoration-underline') { return 'text-decoration: underline;' }
    if ($inner -match '^scale-x-(\d+)$') { return "transform: translate(var(--fhp-tx,0),var(--fhp-ty,0)) scaleX($($Matches[1]));" }
    if ($inner -match '^scale-y-(\d+)$') { return "transform: translate(var(--fhp-tx,0),var(--fhp-ty,0)) scaleY($($Matches[1]));" }
    return $null
}

$unresolved = New-Object System.Collections.Generic.List[string]

# --- flat base rules ---
$flat = @{}
foreach ($name in $BASE) {
    $d = Resolve-Decl $name
    if ($d) { $flat[$name] = $d } else { $unresolved.Add($name) }
}
foreach ($k in ($flat.Keys | Sort-Object)) {
    [void]$sb.AppendLine(".$k {")
    foreach ($ln in ($flat[$k] -split "`n")) { [void]$sb.AppendLine("  $ln") }
    [void]$sb.AppendLine('}')
}
[void]$sb.AppendLine('')

# --- hover / focus variants, resolved against the same base rules ---
if ($Hover.Count) {
    [void]$sb.AppendLine('/* ---- hover / focus variants ---- */')
    foreach ($name in ($Hover | Sort-Object)) {
        $m = [regex]::Match($name, '^fhp-(hover|focus|last|ltr|rtl|first)-(.+)$')
        $st = $m.Groups[1].Value; $inner = $m.Groups[2].Value
        $d = Resolve-Decl ('fhp-' + $inner)
        if (-not $d) { $d = Resolve-Logical $st $inner }
        if (-not $d) { $unresolved.Add($name); continue }
        switch ($st) {
            'focus' { $pseudo = ':focus' }
            'last'  { $pseudo = ':last-child' }
            'first' { $pseudo = ':first-child' }
            'hover' { $pseudo = ':hover' }
            'ltr'   { $pseudo = '[dir="ltr"] &, :dir(ltr) &' }
            'rtl'   { $pseudo = '[dir="rtl"] &, :dir(rtl) &' }
        }
        [void]$sb.AppendLine(".$name$pseudo {")
        foreach ($ln in ($d -split "`n")) { [void]$sb.AppendLine("  $ln") }
        [void]$sb.AppendLine('}')
    }
    [void]$sb.AppendLine('')
}

# --- group-hover variants: the .fhp-group wrapper carries the state ---
if ($GroupHover.Count) {
    [void]$sb.AppendLine('/* ---- group-hover variants (parent carries .fhp-group) ---- */')
    foreach ($name in ($GroupHover | Sort-Object)) {
        $inner = $name -replace '^fhp-group-hover-', ''
        $d = Resolve-Decl ('fhp-' + $inner)
        if (-not $d) { $unresolved.Add($name); continue }
        [void]$sb.AppendLine(".fhp-group:hover .$name {")
        foreach ($ln in ($d -split "`n")) { [void]$sb.AppendLine("  $ln") }
        [void]$sb.AppendLine('}')
    }
    [void]$sb.AppendLine('')
}

# --- breakpoint rules, smallest first so lg wins over md, etc. ---
foreach ($bp in @('sm', 'md', 'lg', 'xl', 'xxl')) {
    $grp = @{}
    foreach ($r in $RESP) {
        if ($r.Bp -ne $bp) { continue }
        $d = Resolve-Decl $r.Core
        if ($d) { $grp[$r.Cls] = $d }
    }
    if ($grp.Count -eq 0) { continue }
    [void]$sb.AppendLine("/* ---- $bp and up (min-width: $($Queries[$bp])) ---- */")
    [void]$sb.AppendLine("@media (min-width: $($Queries[$bp])) {")
    foreach ($k in ($grp.Keys | Sort-Object)) {
        [void]$sb.AppendLine("  .$k {")
        foreach ($ln in ($grp[$k] -split "`n")) { [void]$sb.AppendLine("    $ln") }
        [void]$sb.AppendLine('  }')
    }
    [void]$sb.AppendLine('}')
    [void]$sb.AppendLine('')
}

[System.IO.File]::WriteAllText($Out, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))

"emitted base rules : " + $flat.Count
"emitted bp rules   : " + ($RESP | Where-Object { Resolve-Decl $_.Core }).Count
"unresolved tokens  : " + $unresolved.Count
$unresolved | Sort-Object | ForEach-Object { "   ? $_" }
"written            : $Out"


