# ---------------------------------------------------------------------------
# _map_add2.ps1 — extra Tailwind -> Bootstrap / fhp-* mappings (part 2).
# ---------------------------------------------------------------------------
@{
    # ---- misc utilities ----
    'tabular-nums'        = 'fhp-nums'
    'font-secondary'      = 'fhp-font-secondary'
    'font-primary'        = 'fhp-font-primary'
    'accent-primary'      = 'fhp-accent-primary'
    'accent-yellow'       = 'fhp-accent-yellow'
    'opacity-10'          = 'fhp-opacity-10'
    'opacity-20'          = 'fhp-opacity-20'
    'opacity-30'          = 'fhp-opacity-30'
    'opacity-40'          = 'fhp-opacity-40'
    'opacity-60'          = 'fhp-opacity-60'
    'opacity-80'          = 'fhp-opacity-80'
    'opacity-90'          = 'fhp-opacity-90'
    'line-clamp-1'        = 'fhp-line-clamp-1'
    'line-clamp-2'        = 'fhp-line-clamp-2'
    'line-clamp-3'        = 'fhp-line-clamp-3'
    'line-clamp-4'        = 'fhp-line-clamp-4'
    'animate-spin'        = 'fhp-spin'
    'animate-pulse'       = 'fhp-pulse'
    'animate-bounce'      = 'fhp-bounce'
    'border-t-transparent'= 'fhp-border-t-transparent'
    'space-y-2'           = 'fhp-space-y-8'
    'space-y-4'           = 'fhp-space-y-16'
    'space-y-6'           = 'fhp-space-y-24'
    'space-x-4'           = 'fhp-space-x-16'
    'divide-y'            = 'fhp-divide-y'
    'divide-x'            = 'fhp-divide-x'
    'translate-y-full'    = 'fhp-translate-y-full'
    'translate-y-1/4'     = 'fhp-translate-y-25'
    'text-clip'           = 'fhp-text-clip'
    'text-ellipsis'       = 'fhp-text-ellipsis'
    'z-10' = 'fhp-z-10'; 'z-20' = 'fhp-z-20'; 'z-30' = 'fhp-z-30'
    'z-40' = 'fhp-z-40'; 'z-50' = 'fhp-z-50'
    'g-6'  = 'g-4'

    # ---- gradients ----
    'bg-gradient-to-r'  = 'fhp-grad-r'
    'bg-gradient-to-l'  = 'fhp-grad-l'
    'bg-gradient-to-t'  = 'fhp-grad-t'
    'bg-gradient-to-b'  = 'fhp-grad-b'
    'bg-gradient-to-tr' = 'fhp-grad-tr'
    'bg-gradient-to-tl' = 'fhp-grad-tl'
    'bg-gradient-to-br' = 'fhp-grad-br'
    'bg-gradient-to-bl' = 'fhp-grad-bl'
    'from-transparent'  = 'fhp-from-transparent'
    'to-transparent'    = 'fhp-to-transparent'
    'from-black'        = 'fhp-from-black'
    'to-black'          = 'fhp-to-black'
    'from-white'        = 'fhp-from-white'
    'to-white'          = 'fhp-to-white'
    'via-black'         = 'fhp-via-black'
    'via-white'         = 'fhp-via-white'

    # ---- direct Bootstrap replacements (no custom CSS needed) ----
    'no-underline'        = 'text-decoration-none'
    'underline'           = 'text-decoration-underline'
    'line-through'        = 'text-decoration-line-through'
    'sr-only'             = 'visually-hidden'
    'list-none'           = 'list-unstyled'
    'pointer-events-none' = 'pe-none'
    'pointer-events-auto' = 'pe-auto'
    'whitespace-nowrap'   = 'text-nowrap'
    'align-baseline'      = 'align-baseline'

    # ---- simple custom helpers ----
    'list-disc'          = 'fhp-list-disc'
    'resize-none'        = 'fhp-resize-none'
    'whitespace-normal'  = 'fhp-ws-normal'
    'break-words'        = 'fhp-break-words'
    'break-all'          = 'fhp-break-all'
    'isolate'            = 'fhp-isolate'
    'auto-rows-fr'       = 'fhp-auto-rows-fr'
    'grid-flow-row'      = 'fhp-grid-flow-row'
    'col-auto'           = 'fhp-col-auto'
    'row-auto'           = 'fhp-row-auto'
    'select-none'        = 'fhp-select-none'
    'select-all'         = 'fhp-select-all'
    'object-contain'     = 'fhp-object-contain'
    'object-cover'       = 'fhp-object-cover'
    'object-center'      = 'fhp-object-center'
    'object-top'         = 'fhp-object-top'
    'not-italic'         = 'fhp-not-italic'
    'mix-blend-multiply' = 'fhp-mix-multiply'
    'mix-blend-screen'   = 'fhp-mix-screen'
    'mix-blend-overlay'  = 'fhp-mix-overlay'
    'fill-current'       = 'fhp-fill-current'
    'stroke-current'     = 'fhp-stroke-current'
    'backdrop-blur'      = 'fhp-backdrop-blur'
    'backdrop-blur-sm'   = 'fhp-backdrop-blur'
    'backdrop-blur-md'   = 'fhp-backdrop-blur'
}